name: style check

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Install codespell
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND='noninteractive' apt-get install -qy codespell

    - name: Run uncrustify check
      run: |
        ./uncrustify.sh
        git diff --exit-code

    - name: Run codespell check
      run: |
        codespell -L parms,cas -S 'openssl-ca,build,*.log' src include test docs

    - name: Install ruff & run checks
      run: |
        python3 -m venv venv
        . venv/bin/activate
        pip install ruff
        ruff format --check --diff test/ && ruff check test/
